renaming jobs in the yaml to try match them with github checks. added final steps for jobs with matrices

diff --git a/.github/workflows/detectors_test.yml b/.github/workflows/detectors_test.yml
--- a/.github/workflows/detectors_test.yml
+++ b/.github/workflows/detectors_test.yml
@@ -12,7 +12,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  test:
+  detectors-test:
     runs-on: ubuntu-latest
     container: jeffersonlab/gemc:dev-almalinux94
     strategy:
@@ -28,4 +28,17 @@ jobs:
         run: |
           ./ci/detectors_test.sh -d ${{ matrix.detector }}
 
-
+  detectors-test-final:
+    needs:
+      - detectors-test
+    runs-on: ubuntu-latest
+    steps:
+      - name: fail
+        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
+        run: |
+          echo "### Some tests failed." >> $GITHUB_STEP_SUMMARY
+          exit 1
+      - name: pass
+        run: |
+          echo "### All tests passed." >> $GITHUB_STEP_SUMMARY
+          exit 0
diff --git a/.github/workflows/experiment_test.yml b/.github/workflows/experiment_test.yml
--- a/.github/workflows/experiment_test.yml
+++ b/.github/workflows/experiment_test.yml
@@ -18,19 +18,17 @@ jobs:
     runs-on: ubuntu-latest
     container: jeffersonlab/gemc:dev-fedora36
     outputs:
-      matrix:  ${{ steps.set-matrix.outputs.matrix }}
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
-      - name: Creates list of gcards
+      - name: Creates list of gcardsde
         uses: actions/checkout@main
       - id: set-matrix
         run: |
           export JSON=$( ./ci/gcards_to_test.sh )
           echo generate-matrix: $JSON
           echo "matrix=$( echo "$JSON" | tr -d '\n' )" >> $GITHUB_OUTPUT
-  
 
   dev-gcards-test:
-    name: ${{ matrix.detector }}
     needs: generate-matrix
     runs-on: ubuntu-latest
     container: jeffersonlab/gemc:dev-almalinux94
@@ -44,5 +42,18 @@ jobs:
         run: |
           ./ci/experiments_test.sh -g ${{ matrix.gcard }}
 
-
-
+  dev-gcards-test-final:
+    needs:
+      - generate-matrix
+      - dev-gcards-test
+    runs-on: ubuntu-latest
+    steps:
+      - name: fail
+        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
+        run: |
+          echo "### Some tests failed." >> $GITHUB_STEP_SUMMARY
+          exit 1
+      - name: pass
+        run: |
+          echo "### All tests passed." >> $GITHUB_STEP_SUMMARY
+          exit 0
diff --git a/.github/workflows/txt_sql_comparison.yml b/.github/workflows/txt_sql_comparison.yml
--- a/.github/workflows/txt_sql_comparison.yml
+++ b/.github/workflows/txt_sql_comparison.yml
@@ -23,7 +23,7 @@ jobs:
           ./ci/report_runs_and_variations.sh  > Summary.md
           cat Summary.md >> $GITHUB_STEP_SUMMARY
 
-  Geometry:
+  TXTSQLGeoComparison:
     needs: Notary
     runs-on: ubuntu-latest
     container: jeffersonlab/gemc:dev-almalinux94
@@ -58,7 +58,7 @@ jobs:
           name: geologs-${{ matrix.detector }}
           path: /root/logs/
 
-  Run:
+  TXTSQLRunGemc:
     needs: Notary
     runs-on: ubuntu-latest
     container: jeffersonlab/gemc:dev-almalinux94
@@ -110,8 +110,8 @@ jobs:
           name: gemclogs-${{ matrix.detector }}-${{ matrix.variation }}
           path: /root/logs/
 
-  GeoResults:
-    needs: Geometry
+  TXTSQLGeoResults:
+    needs: TXTSQLGeoComparison
     runs-on: ubuntu-latest
     steps:
       - name: Collect logs
@@ -129,8 +129,8 @@ jobs:
           done < comparison.log
           cat Summary.md >> $GITHUB_STEP_SUMMARY
 
-  DigiResults:
-    needs: Run
+  TXTSQLDigiResults:
+    needs: TXTSQLRunGemc
     runs-on: ubuntu-latest
     steps:
       - name: Collect logs
@@ -171,3 +171,20 @@ jobs:
             fi
           done
           cat Summary.md >> $GITHUB_STEP_SUMMARY
+          
+
+  txt-sql-final:
+    needs:
+      - TXTSQLGeoResults
+      - TXTSQLRunGemc
+    runs-on: ubuntu-latest
+    steps:
+      - name: fail
+        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
+        run: |
+          echo "### Some tests failed." >> $GITHUB_STEP_SUMMARY
+          exit 1
+      - name: pass
+        run: |
+          echo "### All tests passed." >> $GITHUB_STEP_SUMMARY
+          exit 0
