updatding experiments with apollo target and adding names to validation workflow to include in required pr validations. this is release 5.14

diff --git a/.github/workflows/tracks_validation.yml b/.github/workflows/tracks_validation.yml
--- a/.github/workflows/tracks_validation.yml
+++ b/.github/workflows/tracks_validation.yml
@@ -35,7 +35,8 @@ jobs:
           echo "BRANCH_NAME=${{ inputs.branch || github.ref_name }}" >> $GITHUB_OUTPUT
 
 
-  ntracks-metrics:
+  tracks-validation:
+    name: Validation (${{ matrix.gen_type }})
     runs-on: ubuntu-latest
     container: jeffersonlab/gemc:dev-almalinux94
     strategy:
@@ -89,3 +90,18 @@ jobs:
             /cvmfs/oasis.opensciencegrid.org/jlab/geant4/geo_build.log
             /cvmfs/oasis.opensciencegrid.org/jlab/geant4/build_coatjava.log
 
+  tracks-validation-final:
+    name: Tracks Validation
+    needs:
+      - tracks-validation
+    runs-on: ubuntu-latest
+    steps:
+      - name: fail
+        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
+        run: |
+          echo "### Some tests failed." >> $GITHUB_STEP_SUMMARY
+          exit 1
+      - name: pass
+        run: |
+          echo "### All tests passed." >> $GITHUB_STEP_SUMMARY
+          exit 0
